first/urls.py
from django.contrib import admin
from django.urls import path, include
import firstApp.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('', firstApp.views.index, name='index'),
    path('', firstApp.views.home, name='home'),
    path('first_app/', include('firstApp.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstApp/urls.py
from django.urls import include, path
from firstApp import views

app_name = 'firstApp'
urlpatterns = [
    # re_path(r'^$', views.index, name='index'),
    path('one', views.one, name='one'),
    path('two', views.two, name='two'),
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('add_category', views.addCategory, name='addCategory'),
    path('add_product', views.addProduct, name='addProduct'),
]

firstApp/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)
    explanation = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    count = models.IntegerField()
    price = models.CharField(max_length=100)
    show = models.BooleanField()
    off = models.IntegerField()
    image = models.ImageField(upload_to='image/', blank=False, null=True,)
    explanation = models.TextField(blank=True)

    def __str__(self):
        return (f'{self.name} : {self.count} : {self.price}')

firstApp/forms.py
from django import forms
from django.core import validators
from .models import Category, Product

# class addCategory(forms.Form):
#     name = forms.CharField()
#     explanation = forms.CharField(widget=forms.Textarea)

    # def clean(self):
    #     acd = super().clean()
    #     email = acd['email']
    #     vmail = acd['vmail']

    #     if email != vmail:
    #         raise forms.ValidationError('MAKE SURE EMAILS MATCH !')

    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError('GOTCHA BOT :(')
    #     return botcatcher

class addCategory(forms.ModelForm):
    class Meta():
        model = Category
        fields = '__all__'


# class addProduct(forms.Form):
#     name = forms.CharField()
#     category = forms.ModelChoiceField(queryset=Category.objects.all())
#     count = forms.IntegerField()
#     price = forms.CharField()
#     show = forms.BooleanField(required=False)
#     off = forms.IntegerField(initial=0)
#     image = forms.ImageField()
#     explanation = forms.CharField(widget=forms.Textarea)

#     def clean(self):
#         d = self.cleaned_data['image']
#         print("#######", d)

class addProduct(forms.ModelForm):
    class Meta():
        model = Product
        fields = '__all__'

firstApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Category, Product
from django.conf import settings
from . import forms

# Create your views here.

def one(request):
    return HttpResponse('This is ONE')

def two(request):
    return render(request, 'firstApp/two.html')

def home(request):
    payload = {}
    return render(request, 'home.html', context=payload)

def products(request):
    prs = Product.objects.all()
    data = {'prs': prs,
            'media': settings.MEDIA_URL,
            'noProducts': len(prs),
            }
    return render(request, 'firstApp/products.html', data)

def addCategory(request):
    form = forms.addCategory()

    if request.method == 'POST':
        form = forms.addCategory(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return home(request)
        else:
            print('ERROR FORM INVALID')
    return render(request, 'firstApp/addCategory.html', {'form':form})

def addProduct(request):
    form = forms.addProduct()

    if request.method == 'POST':
        form = forms.addProduct(request.POST, request.FILES)
        if form.is_valid():
            form.save(commit=True)
            return home(request)
        else:
            print('ERORR FROM INVALID')
    return render(request, 'firstApp/addProduct.html', {'form':form})

templates/firstApp/addCategory.html
{% extends "firstApp/base.html" %}

{% block body_block %}
    <div class='jumbotron'>
        <form action="" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
{% endblock body_block %}

templates/firstApp/addProduct.html
{% extends "firstApp/base.html" %}

{% block body_block %}
    <div class='jumbotron'>
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
{% endblock body_block %}

templates/firstApp/base.html
<!doctype html>
{% load static %}
<html>
    <head>
        <title>First</title>
        <link rel='stylesheet' href='{%static 'css/bootstrap.css' %}'>
        <link rel='stylesheet' href='{%static 'css/style.css' %}'>
        <script src='{%static 'js/jquery-3.5.1.min.js' %}'></script>
        <script src='{%static 'js/bootstrap.js' %}'></script>
    </head>
    <body>
        <nav class='navbar navbar-dark bg-dark navbar-expand-lg'>
            <a class='navbar-brand' href='#'>First</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'home'%}">Home</a>
                    <a class="nav-item nav-link" target="_blank" href="{% url 'admin:index'%}">Admin</a>
                    <a class="nav-item nav-link" href="{% url 'firstApp:products'%}">Products</a>
                    <!-- <a class="nav-item nav-link" href="{% url 'firstApp:one'%}">One</a>
                    <a class="nav-item nav-link" href="{% url 'firstApp:two'%}">Two</a> -->
                    <a class="nav-item nav-link" href="{% url 'firstApp:addCategory'%}">add_category</a>
                    <a class="nav-item nav-link" href="{% url 'firstApp:addProduct'%}">add_product</a>
                </div>
            </div>
        </nav>
        <br><br>

        <div class="container">
            {% block body_block %}
            {% endblock body_block%}
            {% block somesome %}
            {% endblock somesome%}
        </div>

    </body>
</html>

templates/firstApp/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Home ;D</title>
        <meta charset="utf-8">
    </head>
    <body>
        <p>Hello this is index.html</p>
        {{ insert_me }}
    </body>
</html>

templates/firstApp/products.html
{% extends "firstApp/base.html" %}

{% block body_block %}
{% load static %}
    {% comment %} <div class='container'>

        
            <table class='table table-striped'>
                <thead>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Count</th>
                    <th scope="col">Price $</th>
                    <th scope="col">Off %</th>
                    <th scope="col">Explanation</th>
                    <th scope="col">Image</ht>
                </thead>
                <tbody>
                    {% if prs %}
                    {% for pr in prs %}
                        <tr>
                            <th scope="row">{{ pr.id }}</th>
                            <td>{{ pr.name }}</td>
                            <td>{{ pr.category }}</td>
                            <td>{{ pr.count }}</td>
                            <td>{{ pr.price }}</td>
                            <td>{{ pr.off }}</td>
                            <td>{{ pr.explanation }}</td>
                            <td><img src={{media}}{{ pr.image }}></td>
                        </tr>
                    {% endfor %}
                    {% else %}
                        <p>Products does not exists</p>
                    {% endif %}
                </tbody>
            </table>
        </div> {% endcomment %}


        {% comment %} {% if prs %}
            <div class="container mt-5 mb-5">
                <div class="p-2 bg-white px-4">
                    <div class="d-flex flex-row justify-content-between">
                        <div class="d-flex flex-row align-items-center filters">
                            <h4>Filters</h4><span class="ml-2">({{ noProducts }} items)</span>
                        </div>
                        <div class="d-flex flex-row align-items-center filters">
                            <div class="d-flex flex-row align-items-center">
                                <h5 class="mt-1">Sort by</h5><span class="ml-2">our price</span><i class="fa fa-angle-down ml-1"></i>
                            </div>
                            <div class="d-flex flex-row align-items-center ml-3"><span>ratings</span><i class="fa fa-angle-down ml-1"></i></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for pr in prs %}
                        <div class="col-md-4 col-lg-4 mt-2">
                            <div class="p-4 bg-white">
                                <div class="d-flex flex-column">
                                    <div><img class="img-fluid img-responsive" src="{{media}}{{ pr.image }}" width="" height="220"></div>
                                    <div class="d-flex flex-column">
                                        <div class="d-flex flex-row justify-content-between align-items-center">
                                            <h5>{{ pr.name }}</h5>
                                            <h6>${{ pr.price }}</h6>
                                        </div>
                                        <div><span>{{ pr.count }}</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                   {% endfor %}
                </div>
            </div>
        {% endif %} {% endcomment %}
    
    <link rel='stylesheet' href='{%static 'css/products.css' %}'>

    {% if prs %}
        <div class="row">
            {% for pr in prs %}
                <div class="col-md-4">
                    <figure class="card card-product-grid card-lg"> <a href="#" class="img-wrap thumbnail" data-abc="true" data-toggle="modal" data-target="#image-gallery" data-image="{{media}}{{ pr.image }}"><img class="img-thumbnail" src="{{media}}{{ pr.image }}"></a>
                        <figcaption class="info-wrap">
                            <div class="row">
                                <div class="col-md-8"> <a href="#" class="title" data-abc="true">{{ pr.name }}</a> </div>
                                   <div class="col-md-4">
                                    <div class="rating text-right"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
                                </div>
                            </div>
                        </figcaption>
                        <div class="bottom-wrap"> <a href="#" class="btn btn-primary float-right" data-abc="true"> Buy now </a>
                            <div class="price-wrap"> <span class="price h5">${{ pr.price }}</span> <br> <small class="text-success">Free shipping</small> </div>
                        </div>
                    </figure>
                </div>
            {% endfor %}
        </div>
        {% comment %}  {% endcomment %}
        
        {% comment %}  {% endcomment %}
    {% endif %}
{% endblock body_block %}

{% block somesome %}
<div class="modal fade" id="image-gallery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="image-gallery-title"></h4>
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <img id="image-gallery-image" class="img-responsive col-md-12" src="">
                    </div>
                    <div class="modal-footer"></div>
                </div>
            </div>
        </div>
        {% endblock somesome%}

templates/firstApp/two.html
{% load static %}
<html>
    <head>
        <title>TWo</title>
        <meta charset="utf-8">
        <link rel='stylesheet' href='{%static 'css/style.css' %}'>
    </head>
    <body>
        <p>Hello this is two.html from firstApp</p>
        <img src='{%static 'images/linux.jpg' %}' alt='uh oh, did not show :('>
    </body>
</html>

templates/home.html
{% extends "firstApp/base.html" %}

{% block body_block %}
    <ul>
        {% comment %} <li><a target='_blank' href='/admin'>Admin</a></li>
        <li><a target='_blank' href='first_app/products'>Products</a></li>
        <li><a target='_blank' href='first_app/one'>firstApp/one</a></li>
        <li><a target='_blank' href='first_app/two'>firstApp/two</a></li>
        <li><a target='_blank' href='first_app/add_category'>firstApp/addCategory</a></li>
        <li><a target='_blank' href='first_app/add_product'>firstApp/add_product</a></li> {% endcomment %}
        <li><a target='_blank' href="{% url 'admin:index'%}">Admin</a></li>
        <li><a target='_blank' href="{% url 'firstApp:products'%}">Products</a></li>
        <li><a target='_blank' href="{% url 'firstApp:one'%}">One</a></li>
        <li><a target='_blank' href="{% url 'firstApp:two'%}">Two</a></li>
        <li><a target='_blank' href="{% url 'firstApp:addCategory'%}">add_category</a></li>
        <li><a target='_blank' href="{% url 'firstApp:addProduct'%}">add_product</a></li>
    </ul>
    <style>
        li{
            font-size: 30px;
        }
    </style>
{% endblock body_block %}